Annotations new features
PMBio/deeprvat pull request #54
Opened 2024-02-20 13:47 UTC by Marcel-Mueck

# What

The new update to the annotation pipeline includes all annotation tools used for the published version of deeprvat, as well as all processing steps needed to create ready-to-run annotation data for the published deeprvat version. 
![annotation_rulegraph](https://github.com/PMBio/deeprvat/assets/23211603/13246d6e-82e0-4564-8370-f19bdd2d647e)

Updates since last push:
- inclusion of AlphaMissense annotations as plugin in VEP
- changed DAG in order to optimize parallelisation
- Allele Frequency, MAF and AF_MB calculated from genotype file
- pipeline includes filtering step for variants based on distance to the nearest exon
- selection of required columns for deeprvat as well as renaming of columns to fit required input is now performed
- abSplice pipeline is now integrated into the DAG
- spliceAI scores are aggregated to spliceAI_delta_sores

# Testing
- since the annotation tools rely on pre-scored data, automatic tests via GitHub actions is not completely possible
- the annotation pipeline was instead tested locally using example data

2024-02-23 10:01 UTC, meyerkm commented
@Marcel-Mueck There seems to be duplicate functions in annotations.py for the following functions: 
- deepripe_score_variant_onlyseq_all
- merge_abscore
- process_annotations

Also, looks like the Read-the-docs build is failing as the docstrings aren't in the correct Sphinx format. See here to adapt: https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html

2024-03-22 08:37 UTC, endast commented on deeprvat/annotations/annotations.py
> +import itertools
This one is never used

2024-03-22 08:38 UTC, endast commented on deeprvat/annotations/annotations.py
> +from typing import List, Optional
This one is never used

2024-03-22 09:09 UTC, endast requested changes

2024-03-22 12:23 UTC, Marcel-Mueck commented on pipelines/annotations.snakefile
> +SNAKEMAKE_WORKDIR = config.get('absplice_tmp_dir') or  absplice_repo_dir /'example'/ 'workflow'
remove

2024-03-22 12:23 UTC, Marcel-Mueck commented on pipelines/annotations.snakefile
> +absplice_repo_dir = Path(config["absplice_repo_dir"])
remove

2024-03-22 12:25 UTC, Marcel-Mueck commented on pipelines/annotations.snakefile
> +vcf_dir = os.path.dirname(vcf_id)
why like this?

2024-03-22 12:46 UTC, Marcel-Mueck commented on pipelines/config/deeprvat_annotation_config.yaml
> +preprocessing_workdir : preprocessing_workdir
named accordingly?

2024-03-22 12:48 UTC, Marcel-Mueck commented on pipelines/resources/absplice.yaml
pip freeze and lock versions

2024-03-22 14:28 UTC, Marcel-Mueck commented on deeprvat/annotations/annotations.py
> +import warnings
rmvd

2024-03-22 14:29 UTC, Marcel-Mueck commented on deeprvat/annotations/annotations.py
> +import itertools
rmvd

2024-03-22 14:30 UTC, Marcel-Mueck commented on deeprvat/annotations/annotations.py
> +from typing import List, Optional
rmvd

2024-03-22 14:45 UTC, Marcel-Mueck commented on pipelines/annotations.snakefile
> +vcf_dir = os.path.dirname(vcf_id)
resolved

2024-03-22 14:46 UTC, Marcel-Mueck commented on pipelines/annotations.snakefile
> +    include: deeprvat_parent_path / 'deeprvat' / 'pipelines'/'resources'/"absplice_splicing_pred_RNA_Snakefile"
done

2024-03-22 14:47 UTC, Marcel-Mueck commented on pipelines/annotations.snakefile
> +absplice_repo_dir = Path(config["absplice_repo_dir"])
needed for default download dir

2024-03-22 14:49 UTC, Marcel-Mueck commented on pipelines/config/deeprvat_annotation_config.yaml
> +preprocessing_workdir : preprocessing_workdir
no <parent directory> name defined in the preprocessing pipeline

2024-03-22 14:55 UTC, Marcel-Mueck commented on pipelines/resources/absplice_download_Snakefile
done

2024-03-22 14:55 UTC, Marcel-Mueck commented on pipelines/resources/absplice_splicing_pred_DNA_Snakefile
done

2024-03-22 14:55 UTC, Marcel-Mueck commented on pipelines/resources/absplice_splicing_pred_RNA_Snakefile
done

2024-03-22 14:57 UTC, Marcel-Mueck commented on pipelines/resources/config_absplice.yaml
> +#vcf: /omics/odcf/analysis/OE0540_projects/ukbb/exomes/all_200k/annotations/tmp/absplice_input/{vcf_id}
rmvd

2024-03-22 14:57 UTC, Marcel-Mueck commented on pipelines/resources/config_absplice.yaml
> +# False by default, you can change this if you want to run on large datasets (see Readme)
removed line

2024-03-22 14:58 UTC, Marcel-Mueck commented on pipelines/resources/environment_gnomad_rocksdb.yaml
> +  # - bioconda::kipoiseq>=0.7
rmvd unnecessary line

2024-03-22 14:59 UTC, Marcel-Mueck commented on pipelines/resources/absplice_download_Snakefile
> +del splicemap5
no idea honestly

2024-03-22 15:01 UTC, Marcel-Mueck commented on pipelines/resources/absplice_splicing_pred_DNA_Snakefile
> +import os
rmvd unnecessary imports

2024-03-22 15:02 UTC, Marcel-Mueck commented on pipelines/resources/absplice_splicing_pred_DNA_Snakefile
> +#vcf_dir = os.path.dirname(absplice_main_conf['vcf'])
rmvd

2024-03-22 15:04 UTC, Marcel-Mueck commented on pipelines/resources/absplice_splicing_pred_DNA_Snakefile
> +        #absplice_dna = config_pred['splicing_pred']['absplice_dna']
rmvd

2024-03-22 15:04 UTC, Marcel-Mueck commented on pipelines/resources/absplice_splicing_pred_DNA_Snakefile
> +        # expand( config_pred['splicing_pred']['absplice_dna'],
rmvd

2024-03-22 15:05 UTC, Marcel-Mueck commented on pipelines/resources/absplice_splicing_pred_RNA_Snakefile
> +from os.path import isfile, join
rmvd unnecessary imports

2024-03-22 15:07 UTC, Marcel-Mueck commented on pipelines/resources/absplice_splicing_pred_RNA_Snakefile
> +import pathlib
changed - line is unnecessary though, I think, bc  Path is imported in main snakemake pipeline, from which this (sub-)pipeline is called

2024-03-22 15:08 UTC, Marcel-Mueck commented on pipelines/resources/absplice_splicing_pred_RNA_Snakefile
> +    path = Path(config_download['splicemap_dir'])
added but see other commend

2024-03-22 15:20 UTC, Marcel-Mueck commented on pipelines/resources/absplice.yaml
done

2024-03-22 15:29 UTC, Marcel-Mueck commented on pipelines/resources/absplice_download_Snakefile
> +import yaml
rmoved unnecessary imports

2024-03-22 15:45 UTC, Marcel-Mueck commented on pipelines/resources/environment_spliceai_rocksdb.yaml
> +    - git+https://github.com/gagneurlab/spliceai_rocksdb.git@master
done

2024-04-09 09:47 UTC, endast approved these changes

2024-04-09 09:56 UTC, merged